package com.lititi.exams.web.dao;

import com.lititi.exams.web.entity.PublishContent;
import com.lititi.exams.web.entity.PublishContentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PublishContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int countByExample(PublishContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int deleteByExample(PublishContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int insert(PublishContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int insertSelective(PublishContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    List<PublishContent> selectByExample(PublishContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    PublishContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PublishContent record, @Param("example") PublishContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PublishContent record, @Param("example") PublishContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PublishContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PublishContent record);


    List<PublishContent> getContentList(@Param("contentCode") String contentCode,@Param("title") String title,@Param("startDate") String startDate,@Param("endDate") String endDate,@Param("publishFlag") Integer publishFlag);

    PublishContent getContentByDate(@Param("contentCode") String contentCode);

    int updatePublishFlag(@Param("contentCode") String contentCode);
}